### ISSUE TITLE
연결된 Github Page를 알 수 있을까요?

### ISSUE THREAD

**Issue by Laeyoung** [Noriter/toy-class#11]
안녕하세요, 이번 소중대 해커톤 멘토로 참여 했던 커먼컴퓨터 장래영 입니다.

혹시 발표 자료에 소개 되어 있는 Github Pages로 배포된걸 볼 수 있을까요?

<img width="688" alt="스크린샷 2022-06-27 오후 4 09 00" src="https://user-images.githubusercontent.com/1391299/175880254-042cd782-c653-47d0-a95f-1cb09d8919b4.png">

**Comment by joseph-106** [comment]
안녕하세요 멘토님 ! 해커톤 팀원으로 참여한 김성중입니다.
해커톤 기간 내에 UI를 적용시키진 못했지만 메인 서버 로직이 포함된 임시 배포 주소는 다음과 같습니다.

https://noriter.github.io/toy-class/

**Comment by Laeyoung** [comment]
배포해 놓으셨군요~😃

Repo 웹사이트 정보에 넣어놓으시면 좋을거에요, 나중에 이 프로젝트를 포폴 중 하나로 쓰신다면 : )
